FROM 047590332772.dkr.ecr.eu-central-1.amazonaws.com/nodejs:16

WORKDIR /usr/src/app

ENV PORT=8086
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ARG API_HOST
ENV API_HOST=$API_HOST
ARG REGION
ENV REGION=$REGION
ARG SECRET_ID
ENV SECRET_ID=$SECRET_ID
ARG USER_SDK_URL
ENV USER_SDK_URL=$USER_SDK_URL

COPY package*.json ./
COPY .npmrc ./

RUN npm install

COPY . .

EXPOSE 8086

CMD [ "npm", "start" ]
