FROM 047590332772.dkr.ecr.eu-central-1.amazonaws.com/nodejs:16

WORKDIR /usr/src/app

ARG PORT
ENV PORT=$PORT
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ARG API_HOST
ENV API_HOST=$API_HOST
ARG REGION
ENV REGION=$REGION
ARG SECRET_ID
ENV SECRET_ID=$SECRET_ID
ARG USER_SDK_URL
ENV USER_SDK_URL=$USER_SDK_URL
ARG API_ENV
ENV API_ENV=$API_ENV

COPY package*.json ./
COPY .npmrc ./

RUN npm install

COPY . .

EXPOSE $PORT

CMD [ "npm", "start" ]
